### ISSUE TITLE
getting error (0 , _immutable.isImmutable) is not a function

### ISSUE THREAD

**Issue by nathanmcwpe** [grommet/jsx-to-string#35] opened 2018-02-15 21:47 UTC
Trying to use this library to generate code blocks inline in StoryBook, however when I try to call jsxToString(component) i'm getting the error 
```
(0 , _immutable.isImmutable) is not a function
```
I checked the immutable-js repo and there does seem to be a similar issue:
https://github.com/facebook/immutable-js/issues/1165

based on a suggestion there i was able to change the line in jsx-to-string/lib/index.js [69]
from `if ((0, _immutable.isImmutable)(item)) {` to `if ((0, _immutable.Iterable.isIterable)(item)) {` and it works... 

is this an issue with this library? Or is it something with immutable 4.0-rc2? The _immutable object definitely doesn't have an isImmutable function as stated. Is there something better than this semi-hacky fix? Thoughts?

**Comment by alansouzati** [comment] 2018-05-23 18:50
let me look into this. sorry for the delayed response.

**Comment by alansouzati** [comment] 2018-05-23 22:01
could not reproduce this. I'm closing this bug. I've updated to latest immutable though. feel free to reopen if you are still facing this.

https://github.com/grommet/jsx-to-string/releases/tag/v1.4.0

**Closed by alansouzati** 2018-05-23 22:01 UTC
